# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=50)),
                ('footageType', models.CharField(choices=[('SF', 'Square Footage'), ('LF', 'Lineal Footage'), ('CT', 'Count')], default='SF', max_length=2)),
                ('productionTime', models.CharField(choices=[('MD', 'Man Day'), ('MH', 'Man Hour'), ('2D', 'Two Man Crew - 1 Day'), ('4D', 'Four Man Crew - 1 Day')], default='MH', max_length=2)),
            ],
        ),
    ]
